version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hairremoval_app
      MYSQL_USER: hairremoval
      MYSQL_PASSWORD: 55730
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hairremoval_app
      SPRING_DATASOURCE_USERNAME: hairremoval
      SPRING_DATASOURCE_PASSWORD: 55730
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: