spring:

#  profiles:
#    active: dev

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    thymeleaf:
      cache: false

  messages:
    basename: i18n/messages
    cache-seconds: 0
    encoding: UTF-8

  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  config: classpath:config/logback-spring.xml

  #local.japan: "japan"

