spring:

#  profiles:
#    active: dev

  server:
    servlet:
      encoding:
      charset: UTF-8
      enabled: true
      force: true

  thymeleaf:
    cache: false

  messages:
    basename: i18n/messages
    cache-duration: 0
    encoding: UTF-8

  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/hairremoval_app
    username: root
    password: 5573
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000


logging:
  config: classpath:config/logback-spring.xml

  #local.japan: "japan"

